name: test_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  
  # Storage
  shared_preferences: ^2.2.1
  sqflite: ^2.0.0+4
  path_provider: ^2.0.11
  path: ^1.8.2
  equatable: ^2.0.5
  flutter_svg: ^2.0.10+1

  # State Management
  flutter_riverpod: ^2.4.0
  flutter_bloc: ^8.1.3

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
 
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

